### PR TITLE
Some refactoring and managing imports better and adding a make file

### PR DESCRIPTION
**Pull request by mihirk**

### CODE REVIEW

**Comment by mihirk** [comment]
@saurabhhirani Whats the status of this request, have you reviewed the changes?

**Comment by BlueJeansNetwork** [comment]
Was caught up in some rootconf activities - went through the changes - thanks for adding the make functionality. Regarding the change where in you've moved inframer.utils to utils and inframer.stores to stores - I had added inframer.utils because other projects might have utils and/or stores and didn't want to clash against that. Can you elaborate on that change and let me know if I am missing something there?  Thanks again for adding these changes.

**Comment by mihirk** [comment]
The change is to avoid doing a python path import. And they won't clash since other projects will have their own modules, and can be imported using module_name.utils. 
The export of PythonPATH is a really big smell, a project should work without setting not required environment variables. If you really want to run it in its own environment then use venv, which I would onyl recommend for fairly big projects.

**Comment by BlueJeansNetwork** [comment]
Understood anad merged. PYTHONPATH was a temp fix so that people can start using this - this should actually not be required if we create a python package and let users to the - pip install inframer-api inframer-collectors.

**Pull request merged**
